module Lib
  module TL1
    module Huawei
      module Message
        class LstBoard < Input
          def initialize: (
            ?dev: parameter?,
            ?did: parameter?,
            ?onu_locate_info: parameter?,
            ?frame_number: parameter?,
            ?slot_number: parameter?,
            ?board_type: parameter?,
            ?show_option: show_options
          ) -> void
          attr_reader dev: parameter?
          attr_reader did: parameter?
          attr_reader onu_locate_info: parameter?
          attr_reader frame_number: parameter?
          attr_reader slot_number: parameter?
          attr_reader board_type: parameter?
          attr_reader show_option: show_options
        end
      end
    end
  end
end
